/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Preguntas;

import static cis_encuestas.EncuestaSatisfaccion.Principal;
import java.applet.AudioClip;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Luis
 */
public class Pregunta4 extends javax.swing.JPanel {
public Clip clip;
public String rute = "/sonidos/";
public AudioClip a;
    /**
     * Creates new form Pregunta4
     */
    public Pregunta4() {
        initComponents();
    }
public void audios(String audio){
        
        a = java.applet.Applet.newAudioClip(getClass().getResource(rute+audio));
        a.play();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gRUPOpREGUNTA4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdbP4EXCELENTE = new javax.swing.JRadioButton();
        rdbP4BUENA = new javax.swing.JRadioButton();
        rdbP4REGULAR = new javax.swing.JRadioButton();
        rdbP4MALA = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btnSound = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Como calificaria la gama de tramites o servicios que ofrece el Centro Impulso?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Califiquelas en una escala del 5 al 10, tomando en cuenta que:");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));

        rdbP4EXCELENTE.setBackground(new java.awt.Color(0, 0, 153));
        gRUPOpREGUNTA4.add(rdbP4EXCELENTE);
        rdbP4EXCELENTE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP4EXCELENTE.setForeground(new java.awt.Color(255, 255, 255));
        rdbP4EXCELENTE.setText("EXCELENTE");

        rdbP4BUENA.setBackground(new java.awt.Color(0, 0, 153));
        gRUPOpREGUNTA4.add(rdbP4BUENA);
        rdbP4BUENA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP4BUENA.setForeground(new java.awt.Color(255, 255, 255));
        rdbP4BUENA.setText("BUENA");

        rdbP4REGULAR.setBackground(new java.awt.Color(0, 0, 153));
        gRUPOpREGUNTA4.add(rdbP4REGULAR);
        rdbP4REGULAR.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP4REGULAR.setForeground(new java.awt.Color(255, 255, 255));
        rdbP4REGULAR.setText("REGULAR");

        rdbP4MALA.setBackground(new java.awt.Color(0, 0, 153));
        gRUPOpREGUNTA4.add(rdbP4MALA);
        rdbP4MALA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP4MALA.setForeground(new java.awt.Color(255, 255, 255));
        rdbP4MALA.setText("MALA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(rdbP4EXCELENTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbP4BUENA)
                .addGap(85, 85, 85)
                .addComponent(rdbP4REGULAR)
                .addGap(80, 80, 80)
                .addComponent(rdbP4MALA)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbP4EXCELENTE)
                    .addComponent(rdbP4BUENA)
                    .addComponent(rdbP4REGULAR)
                    .addComponent(rdbP4MALA))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGUIENTE");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sonido.png"))); // NOI18N
        btnSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSound, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel2))
                        .addComponent(jLabel1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnSound, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!rdbP4EXCELENTE.isSelected()&& !rdbP4BUENA.isSelected() && !rdbP4REGULAR.isSelected() && !rdbP4MALA.isSelected()){
            JOptionPane.showMessageDialog(null, "Debes contestar la pregunta");
        } else {
        
        Pregunta4();
        
        Pregunta5 p = new Pregunta5();
        p.setSize(830, 350);
        p.setLocation(5,5);
        
        Principal.removeAll();
        Principal.add(p, BorderLayout.CENTER);
        Principal.revalidate();
        Principal.repaint();}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoundActionPerformed
        if (btnSound.isSelected()){
            audios("saPregunta4.wav");
        }else{
            a.stop();
        }
    }//GEN-LAST:event_btnSoundActionPerformed

    public void Pregunta4(){
       if(rdbP4EXCELENTE.isSelected()){
           String sql = "Update preguntas set excelente = excelente + 1 where clavepeguntas = 4";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
       if(rdbP4BUENA.isSelected()){
           String sql = "Update preguntas set buena = buena + 1 where clavepeguntas = 4";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
       if(rdbP4REGULAR.isSelected()){
           String sql = "Update preguntas set regular = regular + 1 where clavepeguntas = 4";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
       if(rdbP4MALA.isSelected()){
           String sql = "Update preguntas set mala = mala + 1 where clavepeguntas = 4";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSound;
    private javax.swing.ButtonGroup gRUPOpREGUNTA4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdbP4BUENA;
    private javax.swing.JRadioButton rdbP4EXCELENTE;
    private javax.swing.JRadioButton rdbP4MALA;
    private javax.swing.JRadioButton rdbP4REGULAR;
    // End of variables declaration//GEN-END:variables
}
