/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Preguntas;

import static cis_encuestas.EncuestaSatisfaccion.Principal;
import java.applet.AudioClip;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Luis
 */
public class Pregunta3 extends javax.swing.JPanel {
public Clip clip;
public String rute = "/sonidos/";
public AudioClip a;
    /**
     * Creates new form Pregunta3
     */
    public Pregunta3() {
        initComponents();
    }
public void audios(String audio){
        
        a = java.applet.Applet.newAudioClip(getClass().getResource(rute+audio));
        a.play();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoPregunta3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdbP3EXCELENTE = new javax.swing.JRadioButton();
        rdbP3REGULAR = new javax.swing.JRadioButton();
        rdbP3MALA = new javax.swing.JRadioButton();
        rdbP3BUENA = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btnSound = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("El tiempo que le tomo realizar su tramite o servicio fue:");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));

        rdbP3EXCELENTE.setBackground(new java.awt.Color(0, 0, 153));
        GrupoPregunta3.add(rdbP3EXCELENTE);
        rdbP3EXCELENTE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP3EXCELENTE.setForeground(new java.awt.Color(255, 255, 255));
        rdbP3EXCELENTE.setText("EXCELENTE");

        rdbP3REGULAR.setBackground(new java.awt.Color(0, 0, 153));
        GrupoPregunta3.add(rdbP3REGULAR);
        rdbP3REGULAR.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP3REGULAR.setForeground(new java.awt.Color(255, 255, 255));
        rdbP3REGULAR.setText("REGULAR");

        rdbP3MALA.setBackground(new java.awt.Color(0, 0, 153));
        GrupoPregunta3.add(rdbP3MALA);
        rdbP3MALA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP3MALA.setForeground(new java.awt.Color(255, 255, 255));
        rdbP3MALA.setText("MALO");

        rdbP3BUENA.setBackground(new java.awt.Color(0, 0, 153));
        GrupoPregunta3.add(rdbP3BUENA);
        rdbP3BUENA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP3BUENA.setForeground(new java.awt.Color(255, 255, 255));
        rdbP3BUENA.setText("BUENO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(rdbP3EXCELENTE)
                .addGap(66, 66, 66)
                .addComponent(rdbP3BUENA)
                .addGap(65, 65, 65)
                .addComponent(rdbP3REGULAR)
                .addGap(64, 64, 64)
                .addComponent(rdbP3MALA)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbP3EXCELENTE)
                    .addComponent(rdbP3BUENA)
                    .addComponent(rdbP3REGULAR)
                    .addComponent(rdbP3MALA))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGUIENTE");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sonido.png"))); // NOI18N
        btnSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSound, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSound, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(!rdbP3EXCELENTE.isSelected()&& !rdbP3BUENA.isSelected() && !rdbP3REGULAR.isSelected() && !rdbP3MALA.isSelected()){
            JOptionPane.showMessageDialog(null, "Debes contestar la pregunta");
        } else {
        
        Pregunta3();
        
        
        Pregunta4 p = new Pregunta4();
        p.setSize(830, 350);
        p.setLocation(5,5);
        
        Principal.removeAll();
        Principal.add(p, BorderLayout.CENTER);
        Principal.revalidate();
        Principal.repaint();}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoundActionPerformed
        if (btnSound.isSelected()){
            audios("saPregunta3.wav");
        }else{
            a.stop();
        }
    }//GEN-LAST:event_btnSoundActionPerformed

    public void Pregunta3(){
       if(rdbP3EXCELENTE.isSelected()){
           String sql = "Update preguntas set excelente = excelente + 1 where clavepeguntas = 3";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
       if(rdbP3BUENA.isSelected()){
           String sql = "Update preguntas set buena = buena + 1 where clavepeguntas = 3";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
       if(rdbP3REGULAR.isSelected()){
           String sql = "Update preguntas set regular = regular + 1 where clavepeguntas = 3";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
       if(rdbP3MALA.isSelected()){
           String sql = "Update preguntas set mala = mala + 1 where clavepeguntas = 3";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoPregunta3;
    private javax.swing.JToggleButton btnSound;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdbP3BUENA;
    private javax.swing.JRadioButton rdbP3EXCELENTE;
    private javax.swing.JRadioButton rdbP3MALA;
    private javax.swing.JRadioButton rdbP3REGULAR;
    // End of variables declaration//GEN-END:variables
}
