/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Preguntas;

import static cis_encuestas.EncuestaSatisfaccion.Principal;
import java.applet.AudioClip;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Luis
 */
public class Pregunta6 extends javax.swing.JPanel {
public Clip clip;
public String rute = "/sonidos/";
public AudioClip a;
    /**
     * Creates new form Pregunta6
     */
    public Pregunta6() {
        initComponents();
    }
public void audios(String audio){
        
        a = java.applet.Applet.newAudioClip(getClass().getResource(rute+audio));
        a.play();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoPregunta6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdbP6EXCELENTE = new javax.swing.JRadioButton();
        rdbP6BUENA = new javax.swing.JRadioButton();
        rdbP6REGULAR = new javax.swing.JRadioButton();
        rdbP6MALA = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btnSound = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("El orden y la limpieza de la oficina le parecio:");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));

        rdbP6EXCELENTE.setBackground(new java.awt.Color(0, 0, 153));
        GrupoPregunta6.add(rdbP6EXCELENTE);
        rdbP6EXCELENTE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP6EXCELENTE.setForeground(new java.awt.Color(255, 255, 255));
        rdbP6EXCELENTE.setText("EXCELENTE");

        rdbP6BUENA.setBackground(new java.awt.Color(0, 0, 153));
        GrupoPregunta6.add(rdbP6BUENA);
        rdbP6BUENA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP6BUENA.setForeground(new java.awt.Color(255, 255, 255));
        rdbP6BUENA.setText("BUENA");

        rdbP6REGULAR.setBackground(new java.awt.Color(0, 0, 153));
        GrupoPregunta6.add(rdbP6REGULAR);
        rdbP6REGULAR.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP6REGULAR.setForeground(new java.awt.Color(255, 255, 255));
        rdbP6REGULAR.setText("REGULAR");

        rdbP6MALA.setBackground(new java.awt.Color(0, 0, 153));
        GrupoPregunta6.add(rdbP6MALA);
        rdbP6MALA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdbP6MALA.setForeground(new java.awt.Color(255, 255, 255));
        rdbP6MALA.setText("MALA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(rdbP6EXCELENTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(rdbP6BUENA)
                .addGap(60, 60, 60)
                .addComponent(rdbP6REGULAR)
                .addGap(91, 91, 91)
                .addComponent(rdbP6MALA)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbP6EXCELENTE)
                    .addComponent(rdbP6BUENA)
                    .addComponent(rdbP6REGULAR)
                    .addComponent(rdbP6MALA))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGUIENTE");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sonido.png"))); // NOI18N
        btnSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSound, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSound)
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(!rdbP6EXCELENTE.isSelected()&& !rdbP6BUENA.isSelected() && !rdbP6REGULAR.isSelected() && !rdbP6MALA.isSelected()){
            JOptionPane.showMessageDialog(null, "Debes contestar la pregunta");
        } else {
         
        Pregunta6();
        
        Pregunta7 p = new Pregunta7();
        p.setSize(830, 350);
        p.setLocation(5,5);
        
        Principal.removeAll();
        Principal.add(p, BorderLayout.CENTER);
        Principal.revalidate();
        Principal.repaint();}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoundActionPerformed
        if (btnSound.isSelected()){
            audios("saPregunta6.wav");
        }else{
            a.stop();
        }
    }//GEN-LAST:event_btnSoundActionPerformed

    public void Pregunta6(){
       if(rdbP6EXCELENTE.isSelected()){
           String sql = "Update preguntas set excelente = excelente + 1 where clavepeguntas = 6";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
       if(rdbP6BUENA.isSelected()){
           String sql = "Update preguntas set buena = buena + 1 where clavepeguntas = 6";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
       if(rdbP6REGULAR.isSelected()){
           String sql = "Update preguntas set regular = regular + 1 where clavepeguntas = 6";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
       if(rdbP6MALA.isSelected()){
           String sql = "Update preguntas set mala = mala + 1 where clavepeguntas = 6";
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
            
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA");

        }catch(Exception e){
            System.out.println(e);
        }
        
       }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoPregunta6;
    private javax.swing.JToggleButton btnSound;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdbP6BUENA;
    private javax.swing.JRadioButton rdbP6EXCELENTE;
    private javax.swing.JRadioButton rdbP6MALA;
    private javax.swing.JRadioButton rdbP6REGULAR;
    // End of variables declaration//GEN-END:variables
}
