/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Preguntas_Percpecion;

import Preguntas.*;
import static cis_encuestas.EncuestaPercepcion.PrincipalP;
import static cis_encuestas.EncuestaSatisfaccion.Principal;
import java.applet.AudioClip;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Luis
 */
public class Pregunta6_percepcion1 extends javax.swing.JPanel {
public String rute = "/sonidos/";
public AudioClip a;
    /**
     * Creates new form Pregunta2
     */
    public Pregunta6_percepcion1() {
        initComponents();
    }
public void audios(String audio){
        
        a = java.applet.Applet.newAudioClip(getClass().getResource(rute+audio));
        a.play();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gruposino = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbCultural = new javax.swing.JComboBox<>();
        cbDeportivo = new javax.swing.JComboBox<>();
        cbEduambiental = new javax.swing.JComboBox<>();
        cbEducativo = new javax.swing.JComboBox<>();
        cbGastronomia = new javax.swing.JComboBox<>();
        cbManualidades = new javax.swing.JComboBox<>();
        cbPlaticas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbRecreativas = new javax.swing.JComboBox<>();
        cbSaludyprevencion = new javax.swing.JComboBox<>();
        cbSaludimagen = new javax.swing.JComboBox<>();
        cbServiciosprofesionales = new javax.swing.JComboBox<>();
        cbOficios = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentarioactividades = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        btnSound1 = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("6. Enumera del 1 al 7 (Tomando en cuenta que 1 es la de mayor importancia y 7 la de menor");

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGUIENTE");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Que actividad consideras que tu centro impulso deberia impartir con mayor continuidad");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cultural");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Deportivo");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Educacion ambiental");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Educativo");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gastronomia");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manualidades");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Platicas formativas");

        cbCultural.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbCultural.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));

        cbDeportivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbDeportivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));
        cbDeportivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDeportivoActionPerformed(evt);
            }
        });

        cbEduambiental.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbEduambiental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));

        cbEducativo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbEducativo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));

        cbGastronomia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbGastronomia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));

        cbManualidades.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbManualidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));

        cbPlaticas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbPlaticas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Recreativas");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Salud y prevencion");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Salud, imagen y bienestar personal");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Servicios profesionales voluntarios");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Oficios");

        cbRecreativas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbRecreativas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));

        cbSaludyprevencion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbSaludyprevencion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));

        cbSaludimagen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbSaludimagen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));

        cbServiciosprofesionales.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbServiciosprofesionales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));

        cbOficios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbOficios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ro", "2do", "3ro", "4to", "5to", "6to", "7mo", "na" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbGastronomia, 0, 64, Short.MAX_VALUE)
                    .addComponent(cbEducativo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbEduambiental, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDeportivo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCultural, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbManualidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbOficios, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbServiciosprofesionales, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbPlaticas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbRecreativas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSaludyprevencion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbSaludimagen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCultural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cbRecreativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDeportivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(cbSaludyprevencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbEduambiental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cbSaludimagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEducativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14)
                    .addComponent(cbServiciosprofesionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGastronomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15)
                    .addComponent(cbOficios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbManualidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cbPlaticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Menciona que talleres, cursos o servicios");

        txtComentarioactividades.setBackground(new java.awt.Color(0, 0, 153));
        txtComentarioactividades.setColumns(20);
        txtComentarioactividades.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtComentarioactividades.setForeground(new java.awt.Color(255, 255, 255));
        txtComentarioactividades.setRows(5);
        txtComentarioactividades.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        jScrollPane1.setViewportView(txtComentarioactividades);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("te gustaria que se implementaran:");

        btnSound1.setBackground(new java.awt.Color(0, 0, 153));
        btnSound1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sonido.png"))); // NOI18N
        btnSound1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        btnSound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSound1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addComponent(btnSound1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(btnSound1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtComentarioactividades.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debes agregar una recomendacion");
        }else{
        Pregunta6_percepcion();
        Recomendaciones();
        Pregunta7_percepcion1 p = new Pregunta7_percepcion1();
        p.setSize(830, 350);
        p.setLocation(5,5);
        
        PrincipalP.removeAll();
        PrincipalP.add(p, BorderLayout.CENTER);
        PrincipalP.revalidate();
        PrincipalP.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void cbDeportivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDeportivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDeportivoActionPerformed

    private void btnSound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSound1ActionPerformed
        if (btnSound1.isSelected()){

            audios("pp6.wav");

        }else{
            a.stop();

        }// TODO add your handling code here:
    }//GEN-LAST:event_btnSound1ActionPerformed
public void Pregunta6_percepcion(){
    String Cultural = cbCultural.getSelectedItem().toString();
    String Deportivo = cbDeportivo.getSelectedItem().toString();
    String Eduambiental = cbEduambiental.getSelectedItem().toString();
    String Educativo = cbEducativo.getSelectedItem().toString();
    String Gastronomia = cbGastronomia.getSelectedItem().toString();
    String Manualidades = cbManualidades.getSelectedItem().toString();
    String Platicasformativas = cbPlaticas.getSelectedItem().toString();
    String Recreativas = cbRecreativas.getSelectedItem().toString();
    String Saludyprevencion = cbSaludyprevencion.getSelectedItem().toString();
    String Saludimagen = cbSaludimagen.getSelectedItem().toString();
    String Serviciosprofesionales = cbServiciosprofesionales.getSelectedItem().toString();
    String Oficios = cbOficios.getSelectedItem().toString();
    
           String sql = "Update pregunta6_percepcion set "+Cultural+" = "+Cultural+" + 1 where id_actividad = 1" ;
           String sql1 = "Update pregunta6_percepcion set "+Deportivo+" = "+Deportivo+" + 1 where id_actividad = 2" ;
           String sql2 = "Update pregunta6_percepcion set "+Eduambiental+" = "+Eduambiental+" + 1 where id_actividad = 3" ;
           String sql3 = "Update pregunta6_percepcion set "+Educativo+" = "+Educativo+" + 1 where id_actividad = 4" ;
           String sql4 = "Update pregunta6_percepcion set "+Gastronomia+" = "+Gastronomia+" + 1 where id_actividad = 5" ;
           String sql5 = "Update pregunta6_percepcion set "+Manualidades+" = "+Manualidades+" + 1 where id_actividad = 6" ;
           String sql6 = "Update pregunta6_percepcion set "+Platicasformativas+" = "+Platicasformativas+" + 1 where id_actividad = 7" ;
           String sql7 = "Update pregunta6_percepcion set "+Recreativas+" = "+Recreativas+" + 1 where id_actividad = 8" ;
           String sql8 = "Update pregunta6_percepcion set "+Saludyprevencion+" = "+Saludyprevencion+" + 1 where id_actividad = 9" ;
           String sql9 = "Update pregunta6_percepcion set "+Saludimagen+" = "+Saludimagen+" + 1 where id_actividad = 10" ;
           String sql10 = "Update pregunta6_percepcion set "+Serviciosprofesionales+" = "+Serviciosprofesionales+" + 1 where id_actividad = 11" ;
           String sql11 = "Update pregunta6_percepcion set "+Oficios+" = "+Oficios+" + 1 where id_actividad = 12" ;
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis2", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            PreparedStatement pst1 = cn.prepareStatement(sql1);
            PreparedStatement pst2 = cn.prepareStatement(sql2);
            PreparedStatement pst3 = cn.prepareStatement(sql3);
            PreparedStatement pst4 = cn.prepareStatement(sql4);
            PreparedStatement pst5 = cn.prepareStatement(sql5);
            PreparedStatement pst6= cn.prepareStatement(sql6);
            PreparedStatement pst7 = cn.prepareStatement(sql7);
            PreparedStatement pst8 = cn.prepareStatement(sql8);
            PreparedStatement pst9 = cn.prepareStatement(sql9);
            PreparedStatement pst10 = cn.prepareStatement(sql10);
            PreparedStatement pst11= cn.prepareStatement(sql11);
            
           
            pst.executeUpdate();
            pst1.executeUpdate();
            pst2.executeUpdate();
            pst3.executeUpdate();
            pst4.executeUpdate();
            pst5.executeUpdate();
            pst6.executeUpdate();
            pst7.executeUpdate();
            pst8.executeUpdate();
            pst9.executeUpdate();
            pst10.executeUpdate();
            pst11.executeUpdate();
            
     
           //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA
        }catch(Exception e){
            System.out.println(e);
        }
        
}
public void Recomendaciones(){
    String Comentario = txtComentarioactividades.getText();
    
   String sql = "Insert into recomendaciones(id, recomendacion) VALUES (NULL, '"+Comentario+"')";
        
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdcis2", "root", "");
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            
          //JOptionPane.showMessageDialog(null, "RESPUESTA GUARDADA
        }catch(Exception e){
            System.out.println(e);
        }
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Gruposino;
    private javax.swing.JToggleButton btnSound1;
    private javax.swing.JComboBox<String> cbCultural;
    private javax.swing.JComboBox<String> cbDeportivo;
    private javax.swing.JComboBox<String> cbEduambiental;
    private javax.swing.JComboBox<String> cbEducativo;
    private javax.swing.JComboBox<String> cbGastronomia;
    private javax.swing.JComboBox<String> cbManualidades;
    private javax.swing.JComboBox<String> cbOficios;
    private javax.swing.JComboBox<String> cbPlaticas;
    private javax.swing.JComboBox<String> cbRecreativas;
    private javax.swing.JComboBox<String> cbSaludimagen;
    private javax.swing.JComboBox<String> cbSaludyprevencion;
    private javax.swing.JComboBox<String> cbServiciosprofesionales;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtComentarioactividades;
    // End of variables declaration//GEN-END:variables
}
